# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gedcom-Date
version:      0.04
version_from: lib/Gedcom/Date.pm
installdirs:  site
requires:
    DateTime:                      0.15
    Params::Validate:              0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
